#+TITLE: XJIRA

A small Emacs package that allows you to define an entry in =org-capture-templates= that will fetch a Jira issue's information.

This is very much a scratch-my-own-itch package and provided as-is.
It depends on =let-alist= and Emacs ≥ 27.1, built with =libjansson=
support.

* Setup

Here's an example capture template:

#+begin_src emacs-lisp
  (customize-set-variable
   'org-capture-templates
   `(("c" "Get Issue from Jira" entry)
     (file+regexp your-org-file some-regexp)
     ,(string-join
       '("* TODO %(xjira-org-capture-issue \"PROJECT\") %(xjira-get 'issue) %(xjira-get 'title)"
         "SCHEDULED: %t"
         ":PROPERTIES:"
         ":REFERENCE: %(eval xjira-host)/browse/%(xjira-get 'issue)"
         ":Reporter: %(xjira-get 'reporter)"
         ":END:"
         "%?"
         "%(xjira-get 'description)")
       "\n")))
#+end_src

=xjira-org-capture-issue= asks you for an issue number and then fetches the required information from Jira via REST. You can then use the various =xjira-get= functions to retrieve the contents of the issue.

Be sure to substitute =PROJECT= for your company's chosen cryptic Jira project shorthand. If you don't pass a string to =xjira-org-capture-issue=, you will be prompted for the project every time you capture something.

* Authentication

You need to set two variables (you'll be prompted for them each time if you haven't.)

#+begin_src emacs-lisp
  (setq xjira-auth "user:pass")
  (setq xjira-host "http://exapmle.com")
#+end_src

You can base64-encode the auth by marking it as a region and using =base64-encode-region= from inside Emacs. Or you can use

#+begin_src shell
  echo -n "user:pass" | base64 -
#+end_src

but be aware that this puts your password in your shell history.
